### ISSUE TITLE
Add org.telegram.messenger.web

### ISSUE THREAD

**Issue by Cholens** [Xposed-Modules-Repo/com.alex193a.tguseridviewer#1]
Please add app name org.telegram.messenger.web

**Comment by kusti420** [comment]
wish README mentioned which telegram it works with. play store version or telegram foss. but yeah it sure aint working with org.telegram.messenger.web

**Comment by alex193a** [comment]
@kusti420 as mentioned in the README, the modules works with Telegram (org.telegram.messenger) and Telegram Beta (org.telegram.messenger.beta)

**Comment by kusti420** [comment]
> @kusti420 as mentioned in the README, the modules works with Telegram (org.telegram.messenger) and Telegram Beta (org.telegram.messenger.beta)

README doesnt mention anything about org.telegram.messenger or org.telegram.messenger.beta.
but yeah having so many official android telegram clients is more confusing than anything

**Comment by alex193a** [comment]
@kusti420 I thought the name of the app was self explanatory enough, the package names can be found in the SCOPE file and are automatically suggested in LSPosed Manager but I'll also add them in the README to be more clearer  😄
By the way, I'm about to release a new version compatible with **Telegram (Web release)**,  it will be available for download in a few minutes 😉

**Comment by kusti420** [comment]
> @kusti420 I thought the name of the app was self explanatory enough, the package names can be found in the SCOPE file and are automatically suggested in LSPosed Manager but I'll also add them in the README to be more clearer 😄 By the way, I'm about to release a new version compatible with **Telegram (Web release)**, it will be available for download in a few minutes 😉

can confirm that v1.2 works with org.telegram.messenger.web. issue can be closed now
